spring:
  application:
    name: product-service
  main:
    banner-mode: off
  profiles:
    active: local
management:
  info:
    java:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
  endpoints:
    web:
      base-path: /product
      exposure:
        include: health,info
info:
  app:
    name: ${spring.application.name}
    description: @project.description@
    version: @project.version@